# Generated by Django 5.2.4 on 2025-07-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(1, 'user'), (2, 'admin')], default=1),
        ),
        migrations.RemoveField(
            model_name='user',
            name='usersname',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
