# Generated by Django 5.2.4 on 2025-07-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_questions_question_rename_quizzes_quiz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(1, 'user'), (2, 'supervisor')], default=1),
        ),
    ]
