# Generated by Django 5.2.4 on 2025-07-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(1, 'user'), (2, 'supervisor')], default=(1, 'user')),
        ),
    ]
