# Generated by Django 5.2.4 on 2025-07-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='types',
        ),
        migrations.DeleteModel(
            name='Types',
        ),
        migrations.AddField(
            model_name='quiz',
            name='types',
            field=models.JSONField(choices=[(1, 'multiple choice'), (2, ' true or false'), (3, 'dropdown'), (4, 'numerical')], default=(1, 'multiple choice')),
        ),
    ]
