# Generated by Django 5.2.4 on 2025-07-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_quiz_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='types',
            field=models.JSONField(choices=[(1, 'multiple choice'), (2, ' true or false'), (3, 'dropdown'), (4, 'numerical')], default=dict),
        ),
    ]
